name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-linters:
    name: Forge Linting
    runs-on: ["self-hosted", "k8s-prod"]

    steps:
      - name: Install Git
        run: sudo apt update && sudo apt install git -y

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: false

      - name: Check format
        run: forge fmt --check
