name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Forge Tests
    runs-on: ["self-hosted", "k8s-prod"]
    container:
      image: bitnami/git:2.47.0

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly
          cache: false
      
      - name: Run tests
        run: forge test --isolate -vvv
        env:
          FOUNDRY_PROFILE: ci
          FORGE_SNAPSHOT_CHECK: true
